version: "3"

vars:
  USERNAME:
    sh: whoami
  HOME_DIR: /Users/{{.USERNAME}}
  HOSTNAME:
    sh: scutil --get ComputerName 2>/dev/null || uname -n
  OS:
    sh: uname -s
  OP: op
  SSH_CONFIG_FILE: "{{.HOME}}/.ssh/config"
  ATUIN_KEY_FILE: "{{.HOME}}/.local/share/atuin/key"
  AGE_KEY_FILE: "{{.HOME}}/.config/sops/age/keys.txt"

tasks:
  default:
    cmds:
      - task --list
    desc: Show available tasks

  build:
    cmds:
      - |
        if [ "{{.OS}}" = "Darwin" ]; then
          echo "Building Nix-Darwin configuration..."
          nix build .#darwinConfigurations.{{.HOSTNAME}}.system
        else
          echo "Building Nix Home Manager configuration for Linux..."
          nix build .#homeConfigurations.linux.activationPackage
        fi
    desc: Build the configuration

  switch:
    cmds:
      - |
        if [ "{{.OS}}" = "Darwin" ]; then
          echo "Switching to the new Nix-Darwin configuration..."
          sudo ./result/sw/bin/darwin-rebuild switch --flake .#{{.HOSTNAME}}
        else
          echo "Activating the new Home Manager configuration for Linux..."
          ./result/activate
        fi
    desc: Apply the new configuration

  update:
    cmds:
      - echo "Updating flake.lock..."
      - nix flake update
    desc: Update the flake.lock file

  clean:
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf result
    desc: Clean build artifacts

  edit:
    cmds:
      - echo "Opening configuration files for editing..."
      - $EDITOR flake.nix
    desc: Edit the configuration

  status:
    cmds:
      - echo "Showing current Nix-Darwin and Home Manager status..."
      - darwin-rebuild dry-run
    desc: Show the current status

  darwin-refresh:
    cmds:
      - echo "Refreshing Nix-Darwin configuration..."
      - sudo darwin-rebuild switch --flake . --show-trace
    desc: Refresh Nix-Darwin configuration

  universal-build:
    deps: [build, switch]
    desc: Build and apply the new configuration based on the OS

  setup-nix:
    cmds:
      - echo "Installing Nix package manager..."
      - curl -sSf -L https://install.lix.systems/lix | sh -s -- install
    desc: Install Nix package manager

  generate-ssh-config:
    cmds:
      - echo "Generating SSH config..."
      - mkdir -p $(dirname {{.SSH_CONFIG_FILE}})
      - "{{.OP}} read 'op://legemi4nfmddm5osivm3cmejem/eallxdl2umzqln63sb46m3w32a/notesPlain' > {{.SSH_CONFIG_FILE}}"
      - echo "SSH config generated in {{.SSH_CONFIG_FILE}}"

  generate-age-key:
    cmds:
      - echo "Generating Age key..."
      - mkdir -p $(dirname {{.AGE_KEY_FILE}})
      - "{{.OP}} read 'op://legemi4nfmddm5osivm3cmejem/rsguk7qmlg2pufvtc7xyd2h6gi/password' > {{.AGE_KEY_FILE}}"
      - echo "Age key generated in {{.AGE_KEY_FILE}}"

  install-fonts:
    cmds:
      - echo "Installing private fonts..."
      - |
        TEMP_DIR=$(mktemp -d)
        FONTS_DIR="{{.HOME_DIR}}/Library/Fonts"

        # Create fonts directory if it doesn't exist
        mkdir -p "$FONTS_DIR"

        # Fetch zip from 1Password and save to temp directory
        {{.OP}} read "op://legemi4nfmddm5osivm3cmejem/lcqj53otepp3bmxpswcr2wajyu/fonts.zip" --out-file="$TEMP_DIR/fonts.zip"

        # Unzip fonts
        unzip -q "$TEMP_DIR/fonts.zip" -d "$TEMP_DIR/fonts"

        # Copy all font files to user fonts directory
        cp "$TEMP_DIR"/fonts/*.{ttf,otf,TTF,OTF} "$FONTS_DIR/" 2>/dev/null || true

        # Cleanup
        rm -rf "$TEMP_DIR"

        echo "Fonts installed in $FONTS_DIR"
    desc: Install private fonts from 1Password
