require('modules/reloader')
require('modules/windowmgmt')
require('modules/layout')
require('modules/skyrocket')
require('modules/applauncher')
require('modules/lazygit')
require('modules/yazi')
require('modules/claude')
